services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: taskmanagement
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    ports:
      - "5454:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: {}